%% Iterate over LASSO method 
% Copyright Robert Niven, 2024, All Rights Reserved

clear k 

'Iterate LASSO **********'

%parameters

k=1;   %matlab problem, cannot start iterations from zero !
kappa(k)=kappa0;    %initial value

while kappa(k) > kappalim      %iterate to kappa limit criterion
    'Iteration **********'
    k=k+1
    kmax=k
    format longEng    
    %same kappa across all columns
    kappa(k)=kappa(k-1)/kappafact
    true_Xi
    Xi=zeros(cc,n);
    for i=1:o
        g=dx(:,i);
        [B,Lasso_FitInfo]=lasso(H,g,'Lambda',kappa(k));
        Xi(:,i)=B;
    end
    Lasso_FitInfo
    Xi_LASSO=Xi

    if knownXi=='Y';     %calc data - known param values in Xi
        diffXi=true_Xi-Xi     %known function
    elseif knownXi=='N'
        diffXi=Xi-Xi          %to show errors; unknown function
    end;

    %2norm quantities
    for i=1:o    %loop over Y dimensions o
        Resid2_LASSO(k,i)= (norm(dx(:,i) - H*Xi(:,i)))^2;
        Reg2_LASSO(k,i)= (norm(Xi(:,i)))^2;
        Jtilde2_LASSO(k,i)=Resid2_LASSO(k,i) + kappa(k) * Reg2_LASSO(k,i);  %Tik obj function 
        %
        Reg1_LASSO(k,i)= (norm(Xi(:,i),1));
        J_LASSO(k,i)=Resid2_LASSO(k,i) + 2*m*kappa(k)*Reg1_LASSO(k,i);         
    end
    Resid2_LASSO(k,:)
    Reg2_LASSO(k,:)
    Jtilde2_LASSO(k,:)     

    Reg1_LASSO(k,:)
    J_LASSO(k,:)    

    % Show and compare the coefficients and generated time series
    Title_text='LASSO method'; 
    if dynsys==1
         Show_comparisons6a;
    elseif hydrolmodel==1 | RRmodel==1
         Show_comparisons8;
    end;

end

'Results from all iterations **********'
format longEng

kspan=[2:1:kmax]; %k data starting from 2
kapspan=[kappa(kmax),kappa0]; 

%true_Xi
%Xi_LASSO

numit_LASSO=kmax
kappa_LASSO = kappa

Resid2_LASSO
Reg2_LASSO
Jtilde2_LASSO  

Reg1_LASSO
J_LASSO

%Title_text='LASSO'; 
Fighead_text='LASSO iterations';

%plot over iterations

%variation of kappa with k, all dimensions
     figure, %omit dummy first point
        semilogy(kspan, kappa_LASSO(2:end), 'm-o', ...
            'MarkerFaceColor','m'), ...
        xlabel('$k$','Interpreter','latex','FontSize',18),...
        ylabel('$\kappa$','FontSize',18), ...
        ylim(kapspan), ...
        title({fighead; Fighead_text},'FontSize',18)
        ax = gca; ax.XAxis.FontSize = 16; ax.YAxis.FontSize = 16;
        fignum=fignum+1; 
        saveas(gcf,fullfile(pwd, dirname,strcat('Fig',int2str(fignum))),'epsc')

if o==1
   %hardwired 1D; plots against kappa
   %awkward format to allow filled markers

    figure, %omit dummy first point
        loglog(kappa_LASSO(2:end), Resid2_LASSO(2:end,1), 'b-^', ...
            'MarkerFaceColor','b'), ...
        xlabel('$\kappa$','Interpreter','latex','FontSize',18),...
        ylabel('Variable','FontSize',18), ...
        xlim(kapspan), ylim([1.0e-30,1.0e5]), ...
        title({fighead; Fighead_text},'FontSize',18)
        ax = gca; ax.XAxis.FontSize = 16; ax.YAxis.FontSize = 16;
        hold on
        loglog(kappa_LASSO(2:end), Reg2_LASSO(2:end,1), 'r-*')
        loglog(kappa(2:end), Jtilde2_LASSO(2:end,1), 'k-s')
        hold off
        legend({'$||\dot{X}_1 - \Theta \Xi_1||^2_2$', ...
        '$||\Xi_1||^2_2$','${J}^{IT}_1$'}, 'Interpreter','latex',...
        'FontSize',16, ...
        'Location','southoutside')
        fignum=fignum+1; 
        saveas(gcf,fullfile(pwd, dirname,strcat('Fig',int2str(fignum))),'epsc')

    figure, %omit dummy first point
        loglog(kappa_LASSO(2:end), Resid2_LASSO(2:end,1), 'b-^', ...
            'MarkerFaceColor','b'), ...
        xlabel('$\kappa$','Interpreter','latex','FontSize',18),...
        ylabel('Variable','FontSize',18), ...
        xlim(kapspan), ylim([1.0e-30,1.0e5]), ...
        title({fighead; Fighead_text},'FontSize',18)
        ax = gca; ax.XAxis.FontSize = 16; ax.YAxis.FontSize = 16;
        hold on
        loglog(kappa_LASSO(2:end), Reg2_LASSO(2:end,1), 'r-*')
        loglog(kappa(2:end), Jtilde2_LASSO(2:end,1), 'k-s')
        hold off
        fignum=fignum+1; 
        saveas(gcf,fullfile(pwd, dirname,strcat('Fig',int2str(fignum))),'epsc')

elseif o==2
   %hardwired 2D; plots against kappa
   %awkward format to allow filled markers

    figure, %omit dummy first point
        loglog(kappa_LASSO(2:end), Resid2_LASSO(2:end,1), 'b-^', ...
            kappa_LASSO(2:end), Resid2_LASSO(2:end,2), 'b--^', ...
            'MarkerFaceColor','b'), ...
        xlabel('$\kappa$','Interpreter','latex','FontSize',18),...
        ylabel('Variable','FontSize',18), ...
        xlim(kapspan), ylim([1.0e-30,1.0e20]), ...
        title({fighead; Fighead_text},'FontSize',18)
        ax = gca; ax.XAxis.FontSize = 16; ax.YAxis.FontSize = 16;
        hold on
        loglog(kappa_LASSO(2:end), Reg2_LASSO(2:end,1), 'r-*', ...
            kappa_LASSO(2:end), Reg2_LASSO(2:end,2), 'r--*')
        loglog(kappa(2:end), Jtilde2_LASSO(2:end,1), 'k-s', ...
            kappa_LASSO(2:end), Jtilde2_LASSO(2:end,2), 'k--s')
        hold off
        legend({'$||\dot{X}_1 - \Theta \Xi_1||^2_2$', ...
        '$||\dot{X}_2 - \Theta \Xi_2||^2_2$', ...
        '$||\Xi_1||^2_2$','$||\Xi_2||^2_2$', ...
        '${J}^{IT}_1$','${J}^{IT}_2$'}, ...
        'Interpreter','latex','FontSize',16, ...
        'Location','southoutside')
        fignum=fignum+1; 
        saveas(gcf,fullfile(pwd, dirname,strcat('Fig',int2str(fignum))),'epsc')

    figure, %omit dummy first point
        loglog(kappa_LASSO(2:end), Resid2_LASSO(2:end,1), 'b-^', ...
            kappa_LASSO(2:end), Resid2_LASSO(2:end,2), 'b--^', ...
            'MarkerFaceColor','b'), ...
        xlabel('$\kappa$','Interpreter','latex','FontSize',18),...
        ylabel('Variable','FontSize',18), ...
        xlim(kapspan), ylim([1.0e-30,1.0e20]), ...
        title({fighead; Fighead_text},'FontSize',18)
        ax = gca; ax.XAxis.FontSize = 16; ax.YAxis.FontSize = 16;
        hold on
        loglog(kappa_LASSO(2:end), Reg2_LASSO(2:end,1), 'r-*', ...
            kappa_LASSO(2:end), Reg2_LASSO(2:end,2), 'r--*')
        loglog(kappa(2:end), Jtilde2_LASSO(2:end,1), 'k-s', ...
            kappa_LASSO(2:end), Jtilde2_LASSO(2:end,2), 'k--s')
        hold off
        fignum=fignum+1; 
        saveas(gcf,fullfile(pwd, dirname,strcat('Fig',int2str(fignum))),'epsc')        

elseif o==3
   %hardwired 3D; plots against kappa
   %awkward format to allow filled markers
    figure, %omit dummy first point
        loglog(kappa_LASSO(2:end), Resid2_LASSO(2:end,1), 'b-^', ...
            kappa_LASSO(2:end), Resid2_LASSO(2:end,2), 'b--^', ...
            kappa_LASSO(2:end), Resid2_LASSO(2:end,3), 'b-.^', ...
            'MarkerFaceColor','b'), ...
        xlabel('$\kappa_j$','Interpreter','latex','FontSize',18),...
        ylabel('Variable','FontSize',18), ...
        xlim(kapspan), ... %ylim([1.0e-30,1.0e20]), ...
        title({fighead; Fighead_text},'FontSize',18)
        ax = gca; ax.XAxis.FontSize = 16; ax.YAxis.FontSize = 16;
        hold on
        loglog(kappa_LASSO(2:end), Reg2_LASSO(2:end,1), 'r-*', ...
            kappa_LASSO(2:end), Reg2_LASSO(2:end,2), 'r--*', ...
            kappa_LASSO(2:end), Reg2_LASSO(2:end,3), 'r-.*')
        loglog(kappa(2:end), Jtilde2_LASSO(2:end,1), 'k-s', ...
            kappa_LASSO(2:end), Jtilde2_LASSO(2:end,2), 'k--s', ...
            kappa_LASSO(2:end), Jtilde2_LASSO(2:end,3), 'k-.s')
        hold off
        legend({'$||\dot{X}_1 - \Theta \Xi_1||^2_2$', ...
        '$||\dot{X}_2 - \Theta \Xi_2||^2_2$', ...
        '$||\dot{X}_3 - \Theta \Xi_3||^2_2$', ...
        '$||\Xi_1||^2_2$','$||\Xi_2||^2_2$','$||\Xi_3||^2_2$', ...
        '${J}^{IT}_1$','${J}^{IT}_2$','${J}^{IT}_3$'}, ...
        'Interpreter','latex','FontSize',16, ...
        'Location','southoutside')
        fignum=fignum+1; 
        saveas(gcf,fullfile(pwd, dirname,strcat('Fig',int2str(fignum))),'epsc')

    figure, %omit dummy first point
        loglog(kappa_LASSO(2:end), Resid2_LASSO(2:end,1), 'b-^', ...
            kappa_LASSO(2:end), Resid2_LASSO(2:end,2), 'b--^', ...
            kappa_LASSO(2:end), Resid2_LASSO(2:end,3), 'b-.^', 'MarkerFaceColor','b'), ...
        xlabel('$\kappa_j$','Interpreter','latex','FontSize',18),...
        ylabel('Variable','FontSize',18), ...
        xlim(kapspan), ... %ylim([1.0e-30,1.0e20]), ...
        title({fighead; Fighead_text},'FontSize',18)
        ax = gca; ax.XAxis.FontSize = 16; ax.YAxis.FontSize = 16;
        hold on
        loglog(kappa_LASSO(2:end), Reg2_LASSO(2:end,1), 'r-*', ...
            kappa_LASSO(2:end), Reg2_LASSO(2:end,2), 'r--*', ...
            kappa_LASSO(2:end), Reg2_LASSO(2:end,3), 'r-.*')
        loglog(kappa(2:end), Jtilde2_LASSO(2:end,1), 'k-s', ...
            kappa_LASSO(2:end), Jtilde2_LASSO(2:end,2), 'k--s', ...
            kappa_LASSO(2:end), Jtilde2_LASSO(2:end,3), 'k-.s')
        hold off
        fignum=fignum+1; 
        saveas(gcf,fullfile(pwd, dirname,strcat('Fig',int2str(fignum))),'epsc')

   %now for Frobenius quantities; 3D only
   %awkward format to allow filled markers
    figure, %omit dummy first point
        loglog(kappa_LASSO(2:end), Resid2_LASSO(2:end,1), 'b-^', ...
            kappa_LASSO(2:end), Resid2_LASSO(2:end,2), 'b--^', ...
            kappa_LASSO(2:end), Resid2_LASSO(2:end,3), 'b-.^', ...
            'MarkerFaceColor','b'), ...
        xlabel('$\kappa_j$','Interpreter','latex','FontSize',18),...
        ylabel('Variable','FontSize',18), ...
        xlim(kapspan), ... %ylim([1.0e-30,1.0e20]), ...
        title({fighead; Fighead_text},'FontSize',18)
        ax = gca; ax.XAxis.FontSize = 16; ax.YAxis.FontSize = 16;
        hold on
        loglog(kappa_LASSO(2:end), Reg1_LASSO(2:end,1), '-*', ...
            kappa_LASSO(2:end), Reg1_LASSO(2:end,2), '--*', ...
            kappa_LASSO(2:end), Reg1_LASSO(2:end,3), '-.*',...
            'Color', '#FF1D8E', 'MarkerEdgeColor','#FF1D8E', ...
            'MarkerFaceColor','#FF1D8E') %hot pink
        loglog(kappa(2:end), J_LASSO(2:end,1), '-s', ...
            kappa_LASSO(2:end), J_LASSO(2:end,2), '--s', ...
            kappa_LASSO(2:end), J_LASSO(2:end,3), '-.s',...
            'Color', '#D2691E', 'MarkerEdgeColor','#D2690E', ...
            'MarkerFaceColor','#D2690E')  %chocolate, orange)
        hold off
        legend({'$||\dot{X}_1 - \Theta \Xi_1||^2_2$', ...
        '$||\dot{X}_2 - \Theta \Xi_2||^2_2$', ...
        '$||\dot{X}_3 - \Theta \Xi_3||^2_2$', ...
        '$||\Xi_1||^1$','$||\Xi_2||^1$','$||\Xi_3||^1$', ...
        '${J}^{Lasso}_1$','${J}^{Lasso}_2$','${J}^{Lasso}_3$'}, ...
        'Interpreter','latex','FontSize',16, ...
        'Location','southoutside')
        fignum=fignum+1; 
        saveas(gcf,fullfile(pwd, dirname,strcat('Fig',int2str(fignum))),'epsc')

    figure, %omit dummy first point
        loglog(kappa_LASSO(2:end), Resid2_LASSO(2:end,1), 'b-^', ...
            kappa_LASSO(2:end), Resid2_LASSO(2:end,2), 'b--^', ...
            kappa_LASSO(2:end), Resid2_LASSO(2:end,3), 'b-.^', ...
            'MarkerFaceColor','b'), ...
        xlabel('$\kappa_j$','Interpreter','latex','FontSize',18),...
        ylabel('Variable','FontSize',18), ...
        xlim(kapspan), ... %ylim([1.0e-30,1.0e20]), ...
        title({fighead; Fighead_text},'FontSize',18)
        ax = gca; ax.XAxis.FontSize = 16; ax.YAxis.FontSize = 16;
        hold on
        loglog(kappa_LASSO(2:end), Reg1_LASSO(2:end,1), '-*', ...
            kappa_LASSO(2:end), Reg1_LASSO(2:end,2), '--*', ...
            kappa_LASSO(2:end), Reg1_LASSO(2:end,3), '-.*',...
            'Color', '#FF1D8E', 'MarkerEdgeColor','#FF1D8E', ...
            'MarkerFaceColor','#FF1D8E') %hot pink
        loglog(kappa(2:end), J_LASSO(2:end,1), '-s', ...
            kappa_LASSO(2:end), J_LASSO(2:end,2), '--s', ...
            kappa_LASSO(2:end), J_LASSO(2:end,3), '-.s',...
            'Color', '#D2691E', 'MarkerEdgeColor','#D2690E', ...
            'MarkerFaceColor','#D2690E')  %chocolate, orange)
        hold off
        fignum=fignum+1; 
        saveas(gcf,fullfile(pwd, dirname,strcat('Fig',int2str(fignum))),'epsc')

elseif o==4
   %hardwired 4D; plots against kappa
   %awkward format to allow filled markers
    figure, %omit dummy first point
        loglog(kappa_LASSO(2:end), Resid2_LASSO(2:end,1), 'b-^', ...
            kappa_LASSO(2:end), Resid2_LASSO(2:end,2), 'b--^', ...
            kappa_LASSO(2:end), Resid2_LASSO(2:end,3), 'b-.^',...
            kappa_LASSO(2:end), Resid2_LASSO(2:end,4), 'b:^', ...
            'MarkerFaceColor','b'), ...
        xlabel('$\kappa$','Interpreter','latex','FontSize',18),...
        ylabel('Variable','FontSize',18), ...
        xlim(kapspan), ylim([1.0e-30,1.0e20]), ...
        title({fighead; Fighead_text},'FontSize',18)
        ax = gca; ax.XAxis.FontSize = 16; ax.YAxis.FontSize = 16;
        hold on
        loglog(kappa_LASSO(2:end), Reg2_LASSO(2:end,1), 'r-*', ...
            kappa_LASSO(2:end), Reg2_LASSO(2:end,2), 'r--*', ...
            kappa_LASSO(2:end), Reg2_LASSO(2:end,3), 'r-.*', ...
            kappa_LASSO(2:end), Reg2_LASSO(2:end,4), 'r:*')
        loglog(kappa(2:end), Jtilde2_LASSO(2:end,1), 'k-s', ...
            kappa_LASSO(2:end), Jtilde2_LASSO(2:end,2), 'k--s', ...
            kappa_LASSO(2:end), Jtilde2_LASSO(2:end,3), 'k-.s', ...
            kappa_LASSO(2:end), Jtilde2_LASSO(2:end,4), 'k:s')
        hold off
        legend({'$||\dot{X}_1 - \Theta \Xi_1||^2_2$', ...
        '$||\dot{X}_2 - \Theta \Xi_2||^2_2$', ...
        '$||\dot{X}_3 - \Theta \Xi_3||^2_2$', ...
        '$||\dot{X}_4 - \Theta \Xi_4||^2_2$', ...
        '$||\Xi_1||^2_2$','$||\Xi_2||^2_2$','$||\Xi_3||^2_2$', '$||\Xi_4||^2_2$', ...
        '${J}^{IT}_1$','${J}^{IT}_2$','${J}^{IT}_3$','${J}^{IT}_4$'}, ...
        'Interpreter','latex','FontSize',16, ...
        'Location','southoutside')
        fignum=fignum+1; 
        saveas(gcf,fullfile(pwd, dirname,strcat('Fig',int2str(fignum))),'epsc')

    figure, %omit dummy first point
        loglog(kappa_LASSO(2:end), Resid2_LASSO(2:end,1), 'b-^', ...
            kappa_LASSO(2:end), Resid2_LASSO(2:end,2), 'b--^', ...
            kappa_LASSO(2:end), Resid2_LASSO(2:end,3), 'b-.^',...
            kappa_LASSO(2:end), Resid2_LASSO(2:end,4), 'b:^', ...
            'MarkerFaceColor','b'), ...
        xlabel('$\kappa$','Interpreter','latex','FontSize',18),...
        ylabel('Variable','FontSize',18), ...
        xlim(kapspan), ylim([1.0e-30,1.0e20]), ...
        title({fighead; Fighead_text},'FontSize',18)
        ax = gca; ax.XAxis.FontSize = 16; ax.YAxis.FontSize = 16;
        hold on
        loglog(kappa_LASSO(2:end), Reg2_LASSO(2:end,1), 'r-*', ...
            kappa_LASSO(2:end), Reg2_LASSO(2:end,2), 'r--*', ...
            kappa_LASSO(2:end), Reg2_LASSO(2:end,3), 'r-.*', ...
            kappa_LASSO(2:end), Reg2_LASSO(2:end,4), 'r:*')
        loglog(kappa(2:end), Jtilde2_LASSO(2:end,1), 'k-s', ...
            kappa_LASSO(2:end), Jtilde2_LASSO(2:end,2), 'k--s', ...
            kappa_LASSO(2:end), Jtilde2_LASSO(2:end,3), 'k-.s', ...
            kappa_LASSO(2:end), Jtilde2_LASSO(2:end,4), 'k:s')
        hold off
        fignum=fignum+1; 
        saveas(gcf,fullfile(pwd, dirname,strcat('Fig',int2str(fignum))),'epsc')        
end 



